print("Hola mundo")
print("Éste es mi primer proyecto de Python")
print (" Este es un 'ejemplo de comillas' ")
print(100)
print (100 + 30)
print("100 + 40")
print ("Esto" + " " + "es una ejemplo" + " " + "para concatenas")
print("Hola, me llamo \"Alejandro\" ")
print("Esto es una salto de linea\n y se usa para saltar lineas")
print("\t esto es una tabulacion de tres caracteres")
print("This isn\'t the words")
print("Esto \\ es una barra invertida")